# general health check
GET {{api-baseuri}}/health
Accept: application/json

### check data health

GET {{api-baseuri}}/data/health
Accept: application/json

### basic search with API key

GET {{api-baseuri}}/data/search/{{search-term}}
Accept: application/json
X-Api-Key: {{api-key}}

### vector search with API key

GET {{api-baseuri}}/data/search-vector/{{search-term}}
Accept: application/json
X-Api-Key: {{api-key}}
