# general health check
GET {{api-baseuri}}/health
Accept: application/json

### check data health

GET {{api-baseuri}}/{{virtual-path}}/health
Accept: application/json

### get openapi specification

GET {{api-baseuri}}/openapi/v1.json
Accept: application/json

### basic search with API key

GET {{api-baseuri}}/{{virtual-path}}/search/{{search-term}}
Accept: application/json
X-Api-Key: {{api-key}}

### vector search with API key

GET {{api-baseuri}}/{{virtual-path}}/search-vector/{{search-term}}
Accept: application/json
X-Api-Key: {{api-key}}
